.gitignore
src/components/tables/CollectionsTable.vue
src/components/tables/SubCollectionsTable.vue
src/store/actions.js

- Maybe sum all subcollections samplesizes and present it at the toplevel?

M5493 Added tabbed subcollections view

---

app-template.html
build/webpack.base.conf.js
build/webpack.prod.conf.js
index.html
package.json
src/main.js
yarn.lock

[FIX] Menu not clickable through inclusion bootstrap and jquery

---

src/components/tables/CollectionsTable.vue
test/unit/specs/components/CollectionsTable.spec.js
test/unit/specs/store/actions.spec.js
test/unit/specs/store/getters.spec.js
test/unit/specs/store/helpers/helpers.spec.js
test/unit/specs/store/mutations.spec.js

M5556: As Directory user I want to see order of magnitude if exact size is not present

---

src/components/tables/CollectionsTable.vue
src/store/actions.js
test/unit/specs/components/CollectionsTable.spec.js
test/unit/specs/store/actions.spec.js
test/unit/specs/store/getters.spec.js
test/unit/specs/store/helpers/helpers.spec.js
test/unit/specs/store/mutations.spec.js

Fix #24: Subcollections are also shown as top level elements

---

.github/PULL_REQUEST_TEMPLATE.md
Jenkinsfile
package.json
test/e2e/nightwatch.conf.js

[CHORE] Add continuous integration for Jenkins

---

package.json
src/components/BiobankExplorerContainer.vue
src/components/ResultHeader.vue
src/components/filters/ActiveFilterList.vue
src/components/filters/FilterContainer.vue
src/components/filters/StringFilter.vue
src/store/actions.js
src/store/getters.js
src/store/helpers/index.js
src/utils/index.js
test/unit/specs/store/actions.spec.js
test/unit/specs/store/helpers/helpers.spec.js
test/unit/specs/utils/utils.spec.js
yarn.lock

Depends on new release of rsql library.
Fixes #33: Search string does not get escaped properly

M5943: As BBMRI-ERIC I want the free text search box on top replaced with a search box in the facet that searches specific fields

---

index.html
src/components/cards/BiobankReportCard.vue
src/components/tables/CollectionsTable.vue
src/components/tables/QualityColumn.vue
src/store/actions.js
src/utils/index.js
test/unit/specs/store/actions.spec.js
test/unit/specs/utils/utils.spec.js

Model + public data: 
[eric_data_quality.xlsx](https://github.com/molgenis/molgenis-app-biobank-explorer/files/2309503/eric_data_quality.xlsx)
Additional dummy data with quality data for Graz biobank:
[eu_bbmri_eric_col_qual_info_2018-08-22_10_47_41.xlsx](https://github.com/molgenis/molgenis-app-biobank-explorer/files/2309523/eu_bbmri_eric_col_qual_info_2018-08-22_10_47_41.xlsx)
[eu_bbmri_eric_bio_qual_info_2018-08-22_10_47_26.xlsx](https://github.com/molgenis/molgenis-app-biobank-explorer/files/2309524/eu_bbmri_eric_bio_qual_info_2018-08-22_10_47_26.xlsx)
Add some more logo's + quality parameters to the quality tables.

M5942  As BBMRI-ERIC I want to show logo's for standards at the biobank level as well

---

Jenkinsfile
package.json
src/components/BiobankExplorerContainer.vue
src/components/ResultHeader.vue
src/components/cards/BiobankCardsContainer.vue
src/store/actions.js
src/store/getters.js
src/store/helpers/index.js
src/store/mutations.js
src/store/state.js
test/unit/specs/store/actions.spec.js
test/unit/specs/store/getters.spec.js
test/unit/specs/store/helpers/helpers.spec.js
test/unit/specs/store/mutations.spec.js
yarn.lock

Based on #34 and #27, merge them first.
- Updated flow typing (not implemented yet)

 M5876: As BBMRI-ERIC I want remove limitation of 100 in negotiator requests

---

src/store/actions.js
src/store/helpers/index.js
test/unit/specs/store/actions.spec.js
test/unit/specs/store/helpers/helpers.spec.js

- Updated flow typing (because of missing flow typing)

Fix/49 Spaces in diagnosis available search not working

---

README.md

Fix #57 Link to model in README.md is broken

---

test/e2e/nightwatch.conf.js

[CHORE] Update SauceLabs jobname

---

src/components/BiobankExplorerContainer.vue
src/store/actions.js
src/store/getters.js
src/store/mutations.js
src/store/state.js
test/unit/specs/store/actions.spec.js
test/unit/specs/store/getters.spec.js
test/unit/specs/store/mutations.spec.js

Directory shows all collection  belonging to a biobank instea…d of only the ones matching the filters
Filter non matching collections from biobank collections

Fix #20 Directory shows all collections 

---

src/components/cards/BiobankCard.vue
src/components/cards/BiobankCardsContainer.vue
test/unit/specs/components/cards/BiobankCard.spec.js
test/unit/specs/components/cards/BiobankCardsContainer.spec.js
test/unit/specs/components/filters/FilterContainer.spec.js

- Ideally biobank card is open if any search option is selected.
initially do not collapse is filter is active
+
add tests for card components

Part of story #6181, Ideally biobank card is open if any search option is selected.

---

test/unit/index.js
test/unit/specs/components/cards/BiobankReportCard.spec.js

Add test for BiobankReportCard to bump coverage up to 80%

---

Jenkinsfile
package.json

[CHORE] moved registries to node template

---

Jenkinsfile

chore(Jenkinsfile): Fix slack integration

---

test/unit/specs/components/cards/BiobankCard.spec.js

task: Add missing stubs for router to avoid error messages in test output

---

Jenkinsfile

[CHORE] Jenkinsfile: updated registry in HUBOT message release cycle

---

package.json

[FIX] yarn build in postversion step

---

src/components/tables/SubCollectionsTable.vue

Fix #83 
- Rename standard to quality
- Use quality components for display

Fix sub collections quality mark

---

CHANGELOG.md

Add changelog to prepare for release

---

src/components/cards/BiobankCard.vue
src/components/tables/QualityColumn.vue
src/components/tables/SubCollectionsTable.vue

feat: Added quality to biobank card

---

src/components/BiobankExplorerContainer.vue
src/components/ResultHeader.vue
src/components/filters/ActiveFilterList.vue
src/components/negotiator/Negotiator.vue

- fix filter pill styling
- fix missing :key in filter loop
Related to: https://github.com/molgenis/molgenis/issues/8264

Restyle buy button to make it pop out more

---

config/index.js

chore(config): Fix proxy config to link to prod to retrieve data

---

src/components/ResultHeader.vue
src/components/cards/BiobankCard.vue
src/components/cards/BiobankCardsContainer.vue
src/components/filters/ActiveFilterList.vue
src/components/tables/QualityColumn.vue
src/components/tables/SubCollectionsTable.vue
src/main.js
src/store/mutations.js
test/unit/specs/store/actions.spec.js

chore(sonar): Fix sonar issues

---

package.json
test/unit/specs/components/filters/CheckboxFilters.spec.js
yarn.lock

Upgrade bootstrap-vue

---

config/index.js

fix: resolving of image paths

---

src/components/BiobankExplorerContainer.vue

fix: disabled negotiator

---

src/components/BiobankExplorerContainer.vue

fix: changed text

---

src/components/negotiator/Negotiator.vue
src/store/actions.js
test/unit/specs/components/filters/FilterContainer.spec.js

feat: show spinner while waiting for negotiator response

---

README.md
src/store/helpers/index.js
test/unit/specs/store/getters.spec.js
test/unit/specs/store/helpers/helpers.spec.js

fix: search name on collections always

---

src/components/cards/BiobankCard.vue
src/components/cards/BiobankReportCard.vue
src/components/cards/CollectionReportCard.vue
src/components/cards/NetworkReportCard.vue
src/components/report-components/ReportDescription.vue
src/components/report-components/ReportSubCollection.vue

Click on the details view of each of these to see an identifier shown below title and above description
- [x ] Functionality works & meets specifications

Added ids to biobank, collection and network cards

---

src/components/cards/CollectionReportCard.vue
src/components/report-components/ReportDetailsList.vue
src/utils/templateMapper.js
test/unit/specs/components/report-components/ReportDetailsList.spec.js

Can you please tell me what formatter you use? Because now looks like more changes then actually are

feat: added biobankid to collection report details

---

src/components/cards/CollectionReportCard.vue
src/utils/templateMapper.js

fix: fixed biobank id flowing through container when too long

---

config/index.js
package.json
src/components/filters/ActiveFilterList.vue
src/components/filters/FilterContainer.vue
src/store/getters.js
src/store/helpers/covid19Helper.js
src/store/helpers/index.js
src/store/mutations.js
src/store/state.js
test/unit/specs/components/filters/FilterContainer.spec.js
test/unit/specs/mockState.js
test/unit/specs/store/actions.spec.js
test/unit/specs/store/getters.spec.js
test/unit/specs/store/helpers/helpers.spec.js
test/unit/specs/store/mutations.spec.js

- changed maxVisibleOptions from 4 to 25

Add an extra covid19 network filter

---

src/components/report-components/ReportDetailsList.vue
test/unit/specs/components/report-components/ReportDetailsList.spec.js

fix: Changed the color of bool values in ReportDetailList

---

src/components/filters/FilterContainer.vue
src/store/actions.js
src/store/getters.js
src/store/mutations.js
src/store/state.js
test/unit/specs/components/filters/FilterContainer.spec.js
test/unit/specs/store/getters.spec.js
test/unit/specs/store/mutations.spec.js

Add network facets

---

src/components/filters/CheckboxFilters.vue
src/store/mutations.js
test/unit/specs/components/filters/CheckboxFilters.spec.js
test/unit/specs/store/mutations.spec.js

feat: add important filters

---

src/components/cards/CollectionReportCard.vue
src/components/filters/CheckboxFilters.vue
src/utils/templateMapper.js
test/unit/specs/utils/templateMapper.spec.js

fix: hide collaboration no values

---

src/components/negotiator/Negotiator.vue

fix: changed color to secondary

---

src/components/filters/ActiveFilterList.vue
src/store/getters.js
test/unit/specs/store/getters.spec.js

fix: covid19 active filters text is now correctly displayed

---

src/components/tables/CollectionsTable.vue

Fixes https://github.com/molgenis/molgenis-app-biobank-explorer/issues/129.
-  Updated flow typing

Make subcollection table collapsible

---

src/components/filters/StringFilter.vue
src/store/getters.js
src/store/mutations.js
test/unit/specs/components/filters/StringFilter.spec.js
test/unit/specs/store/getters.spec.js

fix: now searchterm is included in active filters as a chip/crumb

---

src/store/mutations.js
test/unit/specs/store/mutations.spec.js

fix: bookmark for biobank quality is now correctly handled

---

src/components/cards/BiobankCard.vue
src/utils/templateMapper.js
test/unit/specs/components/cards/BiobankCard.spec.js

fix: collections are now sorted alphabetically

---

Jenkinsfile

fix(jenkins): Wrong repository string for publishing new version

---

Jenkinsfile
docker/config/default.conf.template
public/index.html
vue.config.js

feat: add preview build

---

package.json
src/components/BiobankExplorerContainer.vue
src/components/ResultHeader.vue
src/store/getters.js
tests/unit/specs/components/ResultHeader.spec.js
tests/unit/specs/store/getters.spec.js
yarn.lock

refactor: moved collectionFound to getters
-  Updated flow typing

feat: replaced negotiator button with cart selection toast

---

Jenkinsfile

chore: fix codecov token in jenkins

---

README.md
public/index.html
public/preview.html
src/components/BiobankExplorerContainer.vue
src/components/ResultHeader.vue
src/components/filters/ActiveFilterList.vue
src/store/helpers/index.js
src/store/state.js
tests/unit/specs/store/getters.spec.js
vue.config.js

fix: make sure to handle the selected country state

---

src/components/cards/BiobankCard.vue
src/components/filters/CheckboxFilters.vue
src/components/filters/DiagnosisAvailableFilters.vue
src/components/filters/StringFilter.vue
src/components/tables/CollectionsTable.vue
src/views/CollectionReport.vue

fix: closes #105, closes #156 and some small styling issues

---

src/App.vue
src/components/BiobankExplorerContainer.vue
src/components/cards/BiobankCardsContainer.vue
src/components/cards/BiobankReportCard.vue
src/components/cards/NetworkReportCard.vue
src/components/filters/ActiveFilterList.vue
src/components/filters/CheckboxFilters.vue
src/components/filters/DiagnosisAvailableFilters.vue
src/components/filters/FilterContainer.vue
src/store/actions.js
src/store/mutations.js
src/views/CollectionReport.vue
tests/unit/specs/components/BiobankExplorerContainer.spec.js
tests/unit/specs/components/cards/BiobankReportCard.spec.js
tests/unit/specs/components/cards/NetworkReportCard.spec.js
tests/unit/specs/components/filters/FilterContainer.spec.js
tests/unit/specs/store/actions.spec.js
tests/unit/specs/store/mutations.spec.js
tests/unit/specs/views/CollectionReport.spec.js

refactor: store naming

---

README.md

- Functionality works & meets specifications
- Clean commits

chore: closes #151, updated readme on how to set Google Analytics ID.

---

src/store/actions.js
src/utils/templateMapper.js
src/views/CollectionReport.vue
tests/unit/specs/store/actions.spec.js

feat: added data-use for DUO

---

src/store/actions.js
src/utils/templateMapper.js

fix: attribute now on correct query

---

babel.config.js
package.json
vue.config.js

fix: Filter Components are now correctly transpiled to work in IE 11

---

src/components/BiobankExplorerContainer.vue

fix: added switch to either display negotiator or podium

---

src/components/cards/BiobankReportCard.vue
src/components/report-components/ReportListRow.vue
src/store/actions.js
src/utils/templateMapper.js
tests/unit/specs/components/report-components/ReportListRow.spec.js
tests/unit/specs/utils/templateMapper.spec.js
vue.config.js

feat: Add uri to collection view chips if present.

---

vue.config.js

chore: add version number to zip

---

src/views/CollectionReport.vue

feat: added 'conditions' to 'data use conditions'

---

package.json

chore: update package.json to push the correct versioned zip.

---

package.json

chore: add versioning to registry upload

---

package.json
src/components/BiobankExplorerContainer.vue
src/components/cards/BiobankCard.vue
src/main.js
src/store/actions.js
src/store/getters.js
src/store/helpers/index.js
src/store/mutations.js
src/store/state.js
src/utils/filterDefinitions.js
src/utils/filterOptions.js
tests/unit/specs/mockData.js
tests/unit/specs/store/getters.spec.js
yarn.lock

feat: add collaboration type facet and show in cart selection

---

package.json
src/main.js
yarn.lock

fix: added latest components-library where the error icon is replace with a more meaningful warning

fix: added latest components-library where the error icon is replaced

---

package.json
public/index.html
public/preview.html
src/components/tables/CollectionsTable.vue
yarn.lock

chore: applied new theme for development
chore: removed unnecessary packages
chore: bumped version of components-library

fix: buttons in collection table are now aligned with header card button

---

src/components/BiobankExplorerContainer.vue
src/components/buttons/CollectionSelectAll.vue
src/components/cards/BiobankCard.vue
src/store/getters.js

fix: added remove all in the cart

feat: remove all items from cart now possible

---

src/App.vue
src/components/cards/BiobankCard.vue
src/components/tables/QualityColumn.vue
src/store/actions.js
src/store/mutations.js
src/store/state.js
tests/unit/specs/store/mutations.spec.js

feat: Add info popover and restyle quality marks of biobank collections

---

package.json
src/App.vue
yarn.lock

fix: popover is now hidden on click anywhere (except other popovers)
fix: removed chai dependancy from the app

fix: popover is now hidden on click anywhere (except other popovers)

---

src/store/helpers/index.js
src/utils/filterOptions.js
tests/unit/specs/store/helpers/helpers.spec.js

fix: Disease filter now uses Code again to search

---

src/store/helpers/index.js
src/utils/index.js
tests/unit/specs/store/helpers/helpers.spec.js

fix: Query uses like now for the same results

---

src/store/helpers/index.js
src/utils/index.js
tests/unit/specs/store/helpers/helpers.spec.js

fix: Like query creates more issues that it solves.

---

Jenkinsfile

chore: specify namespace in kubernetes as name

---

package.json
src/components/filters/CovidFilter.vue
src/components/filters/FilterContainer.vue
tests/unit/specs/components/filters/FilterContainer.spec.js
vue.config.js
yarn.lock

I have fixed the styling of the component to vue-bootstrap version
Also fixed the event to be in line of the standard (using kebab case)
Consolidated the checkbox in the components-library so we dont have to copy paste it. (DRY)

Satisfy All Component

---

src/store/mutations.js

fix: added decodeURIComponent to search

---

src/App.vue
src/components/filters/ActiveFilterList.vue
src/store/actions.js
tests/unit/specs/store/actions.spec.js

url is editable again, also fixed active filters not updating when no query was done

fix: url is editable again, also fixed active filters not updating

---

.eslintrc.js
src/components/BiobankExplorerContainer.vue
src/components/buttons/CollectionSelectAll.vue
src/components/buttons/CollectionSelector.vue
src/components/cards/BiobankCard.vue
src/components/cards/BiobankCardsContainer.vue
src/components/cards/CollectionReportInfoCard.vue
src/components/cards/NetworkReportCard.vue
src/components/filters/CovidFilter.vue
src/components/filters/CovidNetworkFilter.vue
src/components/filters/FilterContainer.vue
src/components/popovers/InfoPopover.vue
src/components/report-components/ReportCollectionDetails.vue
src/components/report-components/ReportDetailsList.vue
src/components/report-components/ReportListRow.vue
src/components/report-components/ReportSubCollection.vue
src/components/tables/CollectionsTable.vue
src/components/tables/QualityColumn.vue
src/components/tables/SubCollectionsTable.vue
src/views/BiobankReport.vue
src/views/CollectionReport.vue

chore: no more > on newline

---

src/components/filters/ActiveFilterList.vue
src/components/filters/FilterContainer.vue
src/store/actions.js
src/store/getters.js
src/store/helpers/index.js
src/store/index.js
src/store/mutations.js
src/store/state.js
src/utils/filterOptions.js
tests/unit/specs/components/filters/FilterContainer.spec.js
tests/unit/specs/mockData.js
tests/unit/specs/store/actions.spec.js
tests/unit/specs/store/getters.spec.js
tests/unit/specs/store/helpers/helpers.spec.js
tests/unit/specs/store/mutations.spec.js

feat: refactored getHumanReadable so we can use it for the history

---

src/App.vue
src/store/helpers/index.js
src/utils/filterOptions.js
src/utils/index.js
tests/unit/specs/store/helpers/helpers.spec.js
tests/unit/specs/utils/utils.spec.js

fix: fixed query application order

fix: expansion of aggregate disease codes works again

---

src/store/mutations.js
tests/unit/specs/store/mutations.spec.js

fix: added backwards compatibility with previously saved diagnosis codes

---

Jenkinsfile

chore: post to right channel

---

package.json
yarn.lock

so that search functionality works as expected in the diagnosis available filter

fix: updated components-library 

---

package.json
src/store/actions.js
tests/unit/specs/store/actions.spec.js
yarn.lock

chore: removed last bit of chai and unneeded vue test utils from molgenis

---

src/components/filters/CovidNetworkFilter.vue

fix: now using the previously selected network as a base for covid19 network filter

---

src/components/BiobankExplorerContainer.vue
src/store/mutations.js

fix: bookmark not updating when selection is removed from cart modal

---

src/utils/filterOptions.js
src/utils/index.js
tests/unit/specs/utils/utils.spec.js

fix: search is now split on empty space and words are now treated separately for better UX

---

src/components/BiobankExplorerContainer.vue
src/store/actions.js
src/store/mutations.js
src/store/state.js
tests/unit/specs/store/mutations.spec.js

- Added to release notes (ammend to fix on #260)

fix: add cart validation status for better bookmark handling

---

Jenkinsfile
package.json
yarn.lock

fix: diagnosis available when searching and then adding a diagnosis resets selection

---

src/App.vue
src/store/mutations.js

fix: querystring is now correctly added to the state using a bookmark

---

src/components/buttons/CollectionSelectAll.vue
src/components/buttons/CollectionSelector.vue
src/components/generators/view-components/hyperlink.vue
src/components/generators/view-components/mref.vue
src/components/generators/view-components/string.vue
src/config/initialCollectionColumns.js
tests/unit/specs/components/generators/view-components/mref.spec.js
tests/unit/specs/components/report-components/ReportCollectionDetails.spec.js
tests/unit/specs/utils/templateMapper.spec.js

fix: updated length of table header to make change readable
fix: made mref-badges wrap when they are too long.

fix: add donor data to collection view

---

src/store/helpers/index.js
tests/unit/specs/store/helpers/helpers.spec.js

fix: icd10 expander is now being used again

---

src/components/filters/MultiFilter.vue

fix: multifilter now always shows checked options on top

---

public/index.html
src/main.js
src/router/index.js
vue.config.js

fix: added google analytics to config so you can now properly configure it

---

README.md

docs: removed spaces

---

src/components/ApplicationHeader.vue
src/components/generators/view-components/mref.vue

fix: application header was on top of molgenis menu

---

src/components/ResultHeader.vue
src/store/getters.js
tests/unit/specs/components/ResultHeader.spec.js

fix: subcollections are now calculated and showed again

---

src/components/ApplicationHeader.vue
src/components/BiobankCardsContainer.vue

fix: more room on top, moved the pagination to the card section top and bottom

---

src/components/cards/BiobankCard.vue
src/config/configManager.js
src/store/state.js
tests/unit/specs/config/configManager.spec.js
vue.config.js

feat: able to show collections first on biobankcards

---

src/components/ApplicationHeader.vue
src/components/buttons/CollectionSelectAll.vue
src/components/buttons/CollectionSelector.vue
src/components/cards/BiobankCard.vue
src/components/cards/CollectionReportInfoCard.vue
src/components/cards/NetworkReportCard.vue
src/components/popovers/NegotiatorSelection.vue
src/components/report-components/ReportDetailsList.vue
src/config/configManager.js
src/config/i18n.js
src/store/getters.js
src/store/state.js
src/views/BiobankReport.vue
src/views/CollectionReport.vue
tests/unit/specs/components/ResultHeader.spec.js
tests/unit/specs/components/buttons/CollectionSelectAll.spec.js
tests/unit/specs/components/buttons/CollectionSelector.spec.js
tests/unit/specs/components/cards/BiobankCard.spec.js
tests/unit/specs/components/cards/NetworkReportCard.spec.js
tests/unit/specs/components/filters/SearchFilter.spec.js
tests/unit/specs/components/popovers/NegotiatorSelection.spec.js
tests/unit/specs/components/report-components/ReportDetailsList.spec.js
tests/unit/specs/config/configManager.spec.js
tests/unit/specs/mockData.js
tests/unit/specs/views/BiobankReport.spec.js
tests/unit/specs/views/CollectionReport.spec.js
vue.config.js

includes:
chore: prepared for more i18n

feat: button and link texts can now be configured

---

package.json
src/components/ApplicationHeader.vue
src/config/configManager.js
src/main.js
src/store/state.js
tests/unit/specs/config/configManager.spec.js
vue.config.js
yarn.lock

feat: hide / show filterbar is now configurable

---

src/config/configManager.js

fix: filterbar now correctly responds to config in database

---

src/components/ApplicationHeader.vue
src/components/buttons/CollectionSelectAll.vue
src/config/facetConfigurator.js
src/config/i18n.js
src/config/initialFilterFacets.js
tests/unit/specs/components/ApplicationHeader.spec.js
tests/unit/specs/components/generators/view-components/string.spec.js

feat: split up filters and reworked their active look

---

src/components/cards/BiobankCard.vue

fix: card contents sometimes overflowing on both collections and biobank details

---

src/store/biobank/biobankMutations.js

fix: stop using vue.set in list iterator

---

src/store/configuration/configurationState.js
src/store/state.js

chore: extracted the configurable state to its own file

---

src/components/ApplicationHeader.vue
src/components/BiobankCardsContainer.vue
src/components/ResultHeader.vue
src/components/cards/BiobankCard.vue
tests/unit/specs/components/ResultHeader.spec.js
tests/unit/specs/views/BiobankCardsContainer.spec.js

fix: usability of application header

---

src/config/facetConfigurator.js

fix: added filterName back to fix cache

---

package.json
src/components/ApplicationHeader.vue
src/components/configuration/DiffEditor.vue
src/components/configuration/FilterConfigUI.vue
src/config/facetConfigurator.js
src/config/initialFilterFacets.js
src/views/ConfigurationScreen.vue
tests/unit/specs/components/ApplicationHeader.spec.js
tests/unit/specs/views/ConfigurationScreen.spec.js
vue.config.js
yarn.lock

Config/config filter UI

---

src/views/ConfigurationScreen.vue

chore: remove console.log

---

src/components/cards/BiobankCard.vue
src/components/filters/CheckboxFilter.vue

fix: checkbox filter can now scroll when there are too many options

---

src/views/ConfigurationScreen.vue
tests/unit/specs/views/ConfigurationScreen.spec.js

configuration screen gives more insight into JSON errors and stops the saving process if any error happens on save

feat: configuration screen gives more insight into JSON errors and stops save process.

---

src/components/cards/BiobankCard.vue
tests/unit/specs/components/cards/BiobankCard.spec.js

fix: calculate container width based on title length

---

src/config/initialBiobankColumns.js
src/config/initialFilterFacets.js
src/store/helpers/index.js
tests/unit/specs/components/cards/BiobankCard.spec.js
tests/unit/specs/store/getters.spec.js
tests/unit/specs/store/helpers/helpers.spec.js
tests/unit/specs/store/mutations.spec.js

feat: add biobank capabilities instead of covid-19 services

---

src/store/biobank/biobankMutations.js
src/store/getters.js

fix: now the count is using the lazy-load mechanism

---

src/store/getters.js
tests/unit/specs/store/getters.spec.js

fix: Added a check to see if a biobankRsql is present

---

src/store/biobank/biobankMutations.js
src/store/getters.js
tests/unit/specs/store/getters.spec.js

fix: counting now correct for filtering on collection and biobank

---

src/config/initialFilterFacets.js
src/store/helpers/index.js

fix: data type and categories filter

---

src/components/filters/SearchFilter.vue
src/store/collection/collectionActions.js
src/store/helpers/index.js
tests/unit/specs/store/getters.spec.js
tests/unit/specs/store/helpers/helpers.spec.js

- [] User documentation updated

feat: text search now also matches on materials and diagnosis

---

src/config/initialFilterFacets.js
src/utils/filterOptions.js

feat: added configuration to be able to remove filter options

---

src/config/initialFilterFacets.js

chore: removed covid19 network as a filter facet

---

src/config/i18n.js
src/utils/templateMapper.js
src/views/BiobankReport.vue
src/views/CollectionReport.vue

feat: added breadcrumb to biobank and collection reports

---

src/views/BiobankReport.vue
src/views/CollectionReport.vue

fix: use '/' instead of biobankexplorer for routing, to keep things consistent

---

src/App.vue
src/config/configManager.js
src/store/configuration/configurationState.js
vue.config.js

feat: add banner that can be enabled from config.

---

src/components/configuration/DiffEditor.vue
src/components/configuration/FilterConfigUI.vue
src/components/configuration/FilterEditor.vue
src/config/facetConfigurator.js
src/config/initialFilterFacets.js
src/views/ConfigurationScreen.vue
tests/unit/specs/views/ConfigurationScreen.spec.js
vue.config.js

feat: filters are now easily editable

---

src/components/configuration/FilterConfigUI.vue
src/config/facetConfigurator.js
src/config/initialFilterFacets.js
src/store/helpers/index.js
src/views/ConfigurationScreen.vue
tests/unit/specs/store/getters.spec.js
tests/unit/specs/store/helpers/helpers.spec.js

fix: you can now specify if a filter should not query the collection table

---

src/config/configManager.js

chore: config is now being generated in a loop based on the initial state

---

Jenkinsfile

build: fix previews

---

src/components/ApplicationHeader.vue
src/store/collection/collectionMutations.js
src/store/getters.js
src/store/mutations.js
src/utils/bookmarkMapper.js
src/utils/filterOptions.js
src/views/BiobankExplorer.vue
tests/unit/specs/components/ApplicationHeader.spec.js
tests/unit/specs/utils/bookmarkMapper.spec.js

fix: fixed satisfy all not being mapped correctly back when coming from a bookmark

---

src/App.vue
src/config/configManager.js
src/store/actions.js
src/store/configuration/configurationState.js
src/store/mutations.js
src/store/state.js
tests/unit/specs/App.spec.js
tests/unit/specs/config/configManager.spec.js
tests/unit/specs/store/mutations.spec.js
vue.config.js

fix: no longer exposing the authentication of the negotiator

---

vue.config.js

fix: add negotiator option to initial config

---

src/App.vue
src/store/actions.js
src/store/configuration/configurationState.js
src/store/mutations.js
src/store/state.js
tests/unit/specs/App.spec.js
tests/unit/specs/store/mutations.spec.js

fix: removed all negotiator table queries

---

Jenkinsfile

fix: make previews available again

---

src/store/biobank/biobankActions.js
src/store/collection/collectionActions.js
src/utils/templateMapper.js
src/views/CollectionReport.vue
tests/unit/specs/utils/templateMapper.spec.js

chore: update app for the latest datamodel

---

src/components/ApplicationHeader.vue
src/components/checkout/CheckOut.vue
src/components/popovers/NegotiatorSelection.vue
src/views/BiobankReport.vue
src/views/CollectionReport.vue

chore: extracted checkout to its own component and added it to bioban…k and collection detail pages
closes #387
closes #385

feat: add request button to collection and biobank detail pages

---

src/components/cards/BiobankCard.vue

fix: only show parent collections in count of biobank card

---

docker/config/default.conf.template
src/components/buttons/CollectionSelectAll.vue
src/components/buttons/CollectionSelector.vue
src/components/checkout/CheckOut.vue
src/components/report-components/ReportCollectionDetails.vue
src/config/i18n.js
src/store/biobank/biobankActions.js
src/store/collection/collectionActions.js
src/views/BiobankReport.vue
src/views/CollectionReport.vue
tests/unit/specs/views/CollectionReport.spec.js

feat: add withdrawn status to biobank page; chore: removed withdrawn from any search results

---

src/App.vue
src/components/cards/BiobankCard.vue
src/components/generators/view-components/quality.vue
src/components/popovers/InfoPopover.vue
src/components/tables/QualityColumn.vue
src/store/actions.js
src/store/mutations.js
src/store/state.js

feat: add quality info to biobank & collections

---

Dockerfile
src/components/generators/custom-view-components/FactsTable.vue

chore: * -> n/a; Grouped together -> Group column

---

Dockerfile
src/components/generators/ViewGenerator.vue
src/components/generators/view-components/mref.vue
src/components/report-components/ReportCollectionDetails.vue
src/config/initialBiobankColumns.js
src/config/initialCollectionColumns.js
src/store/biobank/biobankActions.js
src/utils/templateMapper.js
tests/unit/specs/components/report-components/ReportCollectionDetails.spec.js
tests/unit/specs/utils/templateMapper.spec.js
vue.config.js

feat: add also_known to biobanks

---

src/config/initialBiobankColumns.js

chore: update configuration for also known in

---

src/App.vue

fix: update layout so that it looks nice in freemarker too

---

src/store/actions.js
src/store/mutations.js

fix: dictionary is now properly fetched and handled again

---

package.json
src/components/generators/custom-view-components/FactsTable.vue
src/views/CollectionReport.vue
vue.config.js

feat: latest star schema frontend implementation

---

src/components/generators/custom-view-components/FactsTable.vue
vue.config.js

fix: facts datamodel changes for sex and age range
